# Generated by Django 2.2.2 on 2019-06-25 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SelectedDevice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hostname', models.CharField(choices=[('MCN', 'MCN'), ('Branch1', 'Branch1'), ('Branch2', 'Branch2')], max_length=100)),
            ],
        ),
    ]
